### ISSUE TITLE
NPE in RspProgressJob

### ISSUE THREAD

**Issue by robstryker** [redhat-developer/intellij-rsp#10]
java.lang.NullPointerException
	at org.jboss.tools.intellij.rsp.model.impl.RspProgressJob.countdown(RspProgressJob.java:73)
	at org.jboss.tools.intellij.rsp.model.impl.RspProgressJob.setJobRemoved(RspProgressJob.java:85)
	at org.jboss.tools.intellij.rsp.model.impl.RspCore.jobRemoved(RspCore.java:201)
	at org.jboss.tools.intellij.rsp.client.IntelliJServerManagementClientImpl.lambda$jobRemoved$2(IntelliJServerManagementClientImpl.java:58)
	at org.jboss.tools.intellij.rsp.client.IntelliJServerManagementClientImpl.lambda$async$0(IntelliJServerManagementClientImpl.java:48)
	at java.lang.Thread.run(Thread.java:745)

## What versions of software are you using?
- Operating System:
- IntelliJ version:
- Intellij-rsp extension version

**Comment by robstryker** [comment]
After analyzing the code, it seems the only way for the latch to be null is if it was never actually started. This means that hte JobFinished registered before the RspJobProgress even started to run.  

This is actually good, because if no latch exists yet, and the thread isn't running yet, it means we can simply do a null check and not notify the latch. When the thread does start running, it will create a new latch and then check the isDone status (which will discover the jobRemoved has been registered already) and end the thread properly. 

So simple NPE check here is sufficient.
