### ISSUE TITLE
Server has state "STOPPED", but it's not

### ISSUE THREAD

**Issue by olkornii** [redhat-developer/intellij-rsp#130]
[kind/bug]

## What versions of software are you using?
- Linux (Fedora 33)
- From "master" branch: https://github.com/redhat-developer/intellij-rsp 
- From "master" branch: https://github.com/redhat-developer/intellij-rsp 

## What did you run exactly?

./gradlew runIde -> Start Community Server Connector by Red Hat -> download tomcat 10.0.8 -> start server -> stop server -> close IDE -> see error -> click "Terminate" -> IDE is frozen

## Actual behavior

![stop_server_intellij_rsp_error](https://user-images.githubusercontent.com/60704619/222120999-a9cbbf23-af1c-4638-a74a-b4c01899a23e.png)

## Expected behavior

No errors.

## Any logs, error output, etc?
`2023-03-01 12:07:49,111 [  27184]   WARN - ion.process.UnixProcessManager - Error killing the process 
java.lang.IllegalStateException: Failed to get PID from an instance of class com.redhat.devtools.intellij.rsp.util.RemoteServerProcess, OS: Linux
        at com.intellij.execution.process.UnixProcessManager.getProcessId(UnixProcessManager.java:66)
        at com.intellij.execution.process.UnixProcessManager.sendSignalToProcessTree(UnixProcessManager.java:116)
        at com.intellij.execution.process.UnixProcessManager.sendSigKillToProcessTree(UnixProcessManager.java:111)
        at com.intellij.execution.process.OSProcessUtil.killProcessTree(OSProcessUtil.java:47)
        at com.intellij.execution.process.OSProcessHandler.killProcessTreeSync(OSProcessHandler.java:249)
        at com.intellij.execution.process.OSProcessHandler.lambda$killProcessTree$1(OSProcessHandler.java:243)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:221)
        at com.intellij.execution.process.UnixProcessManager.getProcessId(UnixProcessManager.java:62)
        ... 14 more
2023-03-01 12:07:49,112 [  27185]   WARN - ution.process.OSProcessHandler - Process has been already terminated: Server apache-tomcat-10.0.8 
`

![intellij-rsp-stop](https://user-images.githubusercontent.com/60704619/222121245-e8fa8e9a-93db-4f4b-ac62-81b1c5b78366.gif)

**Comment by robstryker** [comment]
Thanks. I've been distracted with QE and random JBT stuff. I'll be revisiting intellij-rsp asap.

**Comment by robstryker** [comment]
Seems the process actually IS terminated, but the IDE does not think it is.

**Comment by robstryker** [comment]
Think I found the solution. Will continue testing and  cleaning up changes
