### ISSUE TITLE
RSP Servers tab freeze

### ISSUE THREAD

**Issue by olkornii** [redhat-developer/intellij-rsp#149]
[kind/bug]

## What versions of software are you using?
- Operating System: Fedora 38
- IntelliJ version: 2023.2.4(Community Edition)
- Intellij-rsp extension version: 0.7.0.109

## What did you run exactly?

RSP Servers tab does not show an actual situation. Expand/hide child elements does not work after deploy (double click on "Red Hat Server Connector"). Can not see deployed app, as result cannot undeploy it.

## Actual behavior

After app deployment, the tab freezes almost completely. Start/Stop/Restart and other commands work properly but without visual changes.

## Expected behavior

RSP Servers tab shows changes. Same as before app deployment.

## Any logs, error output, etc?

Steps to reproduce:
1. Install Red Hat Server Connector
2. Create/Download Wildfly/EAP server
3. Start it
4. Add deployment -> select java-webapp.war -> Deploy success
5. Try to expand Wildfly server in RSP Servers view -> Nothing happens (Bug) (see error log)
6. Stop server - > server stopped -> in RSP Servers view shows WildflyServer [STARTED...] (Bug)
7. Stop Connector -> Start -> Server is duplicated (Bug)

java-webapp.war: https://github.com/redhat-developer/vscode-server-connector/blob/master/test/resources/java-webapp.war 

error log:
```
2023-11-01 14:05:37,265 [  36693] SEVERE - #c.i.u.c.Invoker - Unexpected character 'G' (code 71) in prolog
 at [row,col {unknown-source}]: [1,2]
com.fasterxml.aalto.WFCException: Unexpected character 'G' (code 71) in prolog
 at [row,col {unknown-source}]: [1,2]
	at com.fasterxml.aalto.in.XmlScanner.reportInputProblem(XmlScanner.java:1333)
	at com.fasterxml.aalto.in.XmlScanner.throwUnexpectedChar(XmlScanner.java:1519)
	at com.fasterxml.aalto.in.XmlScanner.reportPrologUnexpChar(XmlScanner.java:1379)
	at com.fasterxml.aalto.in.StreamScanner.nextFromProlog(StreamScanner.java:187)
	at com.fasterxml.aalto.stax.StreamReaderImpl.next(StreamReaderImpl.java:790)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.buildDocument(JSvgDocumentFactory.kt:95)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.createJSvgDocument(JSvgDocumentFactory.kt:36)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.createJSvgDocument$default(JSvgDocumentFactory.kt:34)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.createJSvgDocument(JSvgDocumentFactory.kt:30)
	at com.intellij.ui.svg.SvgKt.renderImage(svg.kt:291)
	at com.intellij.ui.svg.SvgKt.access$renderImage(svg.kt:1)
	at com.intellij.ui.svg.SvgKt.loadSvgAndCacheIfApplicable-F6nGey4(svg.kt:562)
	at com.intellij.ui.icons.ImageCacheKt.doLoadByDescriptor(imageCache.kt:290)
	at com.intellij.ui.icons.ImageCacheKt.loadByDescriptorWithoutCache(imageCache.kt:177)
	at com.intellij.ui.icons.ImageCacheKt.loadImage(imageCache.kt:139)
	at com.intellij.ui.icons.ImageDataByPathResourceLoader.loadImage(ImageDataByUrlLoader.kt:65)
	at com.intellij.ui.icons.CachedImageIcon.loadImage$intellij_platform_util_ui(CachedImageIcon.kt:313)
	at com.intellij.ui.icons.ScaledIconCache.getOrScaleIcon(ScaledIconCache.kt:43)
	at com.intellij.ui.icons.CachedImageIcon.resolveActualIcon(CachedImageIcon.kt:158)
	at com.intellij.ui.icons.CachedImageIcon.getIconWidth(CachedImageIcon.kt:119)
	at com.intellij.ui.SimpleColoredComponent.computePreferredSize(SimpleColoredComponent.java:436)
	at com.intellij.ui.SimpleColoredComponent.getPreferredSize(SimpleColoredComponent.java:404)
	at com.intellij.ui.tree.ui.DefaultTreeUI$2.getNodeDimensions(DefaultTreeUI.java:585)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:497)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1344)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.createNodeAt(VariableHeightLayoutCache.java:767)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.treeNodesInserted(VariableHeightLayoutCache.java:476)
	at com.intellij.ui.tree.ui.DefaultTreeUI$3.treeNodesInserted(DefaultTreeUI.java:627)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.treeNodesInserted(BasicTreeUI.java:4368)
	at com.intellij.util.ui.tree.TreeModelListenerList.treeNodesInserted(TreeModelListenerList.java:85)
	at com.intellij.ui.tree.AsyncTreeModel.treeNodesInserted(AsyncTreeModel.java:364)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.setNode(AsyncTreeModel.java:698)
	at com.intellij.ui.tree.AsyncTreeModel$Command.accept(AsyncTreeModel.java:475)
	at com.intellij.ui.tree.AsyncTreeModel.lambda$submit$12(AsyncTreeModel.java:293)
	at com.intellij.util.concurrency.Invoker$Wrapper.get(Invoker.java:329)
	at com.intellij.util.concurrency.Invoker$Wrapper.get(Invoker.java:320)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:306)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:186)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:165)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:193)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:690)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:593)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:593)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2023-11-01 14:05:37,269 [  36697] SEVERE - #c.i.u.c.Invoker - IntelliJ IDEA 2023.2.4  Build #IC-232.10203.10
2023-11-01 14:05:37,269 [  36697] SEVERE - #c.i.u.c.Invoker - JDK: 17.0.8.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-11-01 14:05:37,269 [  36697] SEVERE - #c.i.u.c.Invoker - OS: Linux

```

**Comment by olkornii** [comment]
@mohitsuman @robstryker looks like a blocker. After app deployment, undeploy is not possible. What do you think?

**Comment by robstryker** [comment]
Fixing in https://github.com/redhat-developer/intellij-rsp/pull/153

**Comment by olkornii** [comment]
Closing. Works for me with intellij-rsp 0.7.0.113.
