### ISSUE TITLE
Error while starting EAP72

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-rsp#15]
Server is then started but no window for that server

Caught exception in terminal thread

```
java.io.IOException: Write end dead
	at java.io.PipedInputStream.read(PipedInputStream.java:310)
	at java.io.FilterInputStream.read(FilterInputStream.java:83)
	at org.jboss.tools.intellij.rsp.util.ExecUtilClone$RedirectedStream.read(ExecUtilClone.java:65)
	at org.jboss.tools.intellij.rsp.util.ExecUtilClone$RedirectedStream.read(ExecUtilClone.java:89)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at com.jediterm.terminal.ProcessTtyConnector.read(ProcessTtyConnector.java:54)
	at com.jediterm.terminal.TtyBasedArrayDataStream.fillBuf(TtyBasedArrayDataStream.java:21)
	at com.jediterm.terminal.TtyBasedArrayDataStream.getChar(TtyBasedArrayDataStream.java:31)
	at com.jediterm.terminal.DataStreamIteratingEmulator.next(DataStreamIteratingEmulator.java:34)
	at com.jediterm.terminal.TerminalStarter.start(TerminalStarter.java:54)
	at com.jediterm.terminal.ui.JediTermWidget$EmulatorTask.run(JediTermWidget.java:363)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by robstryker** [comment]
https://stackoverflow.com/questions/5453525/write-end-dead-exception-using-pipedinputstream-java

**Comment by robstryker** [comment]
I've been digging into this and looking for answers online, but I think I need a java expert to advise. Most comments on SO / github seem to indicate the writer is expected to be a single thread, but we don't have that here. Instead our model arbitrarily receives events from the RSP (though it's assumed a single connection is a single thread since we use lsp4j.jsonrpc) so I'm not fully sure where the error is coming from.
