### ISSUE TITLE
Can't download/update RSP Server

### ISSUE THREAD

**Issue by ghost** [redhat-developer/intellij-rsp#157]
[kind/bug]

## What versions of software are you using?
- Operating System: Linux Manjaro 23.1.1
- IntelliJ version: 2023.3.2
- Intellij-rsp extension version: 0.8.0.Final.118

## What did you run exactly?

- Open Intellij
- Download Server Connector by Red Hat
- Click right mouse button to show options
- Click Download/Update RSP server

## Actual behavior
Nothing happens, only shows [MISSING]

## Expected behavior
Download/Update the RSP server

## Any logs, error output, etc?
```
Exception in thread "Updating RSP Red Hat Server Connector" java.lang.NoSuchMethodError: 'com.redhat.devtools.intellij.telemetry.core.service.TelemetryMessageBuilder$Message com.redhat.devtools.intellij.telemetry.core.service.TelemetryMessageBuilder$ActionMessage.property(java.lang.String, java.lang.String)'
	at com.redhat.devtools.intellij.rsp.telemetry.TelemetryService.generateTelemetry(TelemetryService.java:120)
	at com.redhat.devtools.intellij.rsp.telemetry.TelemetryService.sendWithType(TelemetryService.java:78)
	at com.redhat.devtools.intellij.rsp.actions.DownloadRspAction$1.run(DownloadRspAction.java:65)
```

**Comment by robstryker** [comment]
Hrmm... I'll look into whether any API changes have occurred and whether a re-release is required. 

Thanks for the heads up. We don't typically update this extension very much because the underlying RSP (the thing you're trying to download) is where 99% of the updates occur. But if there's an issue here we'll of course move to fix it ASAP. 

Sorry for the inconvenience. I'll try to fast-track this as it's a blocker.

**Comment by robstryker** [comment]
https://github.com/redhat-developer/intellij-quarkus/issues/1301#issuecomment-1870161138  has a comment on the issue:

While the team is on vacation, please manually downgrade the telemetry plugin to 1.0.0.44: https://plugins.jetbrains.com/plugin/16209-telemetry-by-red-hat/edit/versions/stable/319318

**Comment by ghost** [comment]
@robstryker it worked! thanks!

**Comment by adietish** [comment]
Compiling against the latest telemetry plugin solves the problem.
@robstryker please review, merge https://github.com/redhat-developer/intellij-rsp/pull/158 and then release a new version of this plugin.
