### ISSUE TITLE
Error when installing rsp into newer idea than 2018.3

### ISSUE THREAD

**Issue by odockal** [redhat-developer/intellij-rsp#63]
[kind/bug]

## What versions of software are you using?
- Operating System: Fedora 32
- IntelliJ version: 2020.2, 2019.3
- Intellij-rsp extension version: built from master (2020-12-08)

## What did you run exactly?
Built plugin locally, opened idea community (2020.2 and 2019.3) and installed built plugin

## Actual behavior
When I open RSP view I can see only `loading` string and get error:
```
java.lang.NoClassDefFoundError: org/jboss/tools/rsp/api/dao/ServerState
	at org.jboss.tools.intellij.rsp.model.impl.RspCore.getServersInRsp(RspCore.java:158)
	at org.jboss.tools.intellij.rsp.ui.tree.RspTreeModel.getChildElements(RspTreeModel.java:56)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:384)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:298)
	at com.intellij.ui.tree.StructureTreeModel$Node.isLeaf(StructureTreeModel.java:559)
	at com.intellij.ui.tree.StructureTreeModel$Node.access$400(StructureTreeModel.java:423)
	at com.intellij.ui.tree.StructureTreeModel.isLeaf(StructureTreeModel.java:334)
	at com.intellij.ui.tree.LeafState.get(LeafState.java:64)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.load(AsyncTreeModel.java:612)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:585)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:478)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:444)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:316)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:77)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:153)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:114)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:56)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:56)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:111)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:77)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:205)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:183)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:541)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:215)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:194)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:183)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.jboss.tools.rsp.api.dao.ServerState PluginClassLoader[PluginDescriptor(name=Runtime Server Protocol Connector by Red Hat, id=org.jboss.tools.intellij.rsp, path=/home/odockal/.local/share/JetBrains/IdeaIC2020.2/intellij-rsp-0.3.0-SNAPSHOT.jar, version=0.3.0-SNAPSHOT)] com.intellij.ide.plugins.cl.PluginClassLoader@498df49d
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:95)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 41 more
```

## Expected behavior
Plugin can be installed without an issue.

**Comment by robstryker** [comment]
I am not able to replicate this using 2020.3

**Comment by robstryker** [comment]
The generated build includes org.jboss.tools.intellij.rsp/lib/org.jboss.tools.rsp.api-0.22.9.Final.jar    along with all the other deps so it'd be strange if it can't find it.

**Comment by robstryker** [comment]
User error, installed wrong jar.
