### ISSUE TITLE
Cannot run cdk command via run server actions: setup-cdk

### ISSUE THREAD

**Issue by odockal** [redhat-developer/intellij-rsp#73]
[kind/bug]

## What versions of software are you using?
- Operating System: f32
- IntelliJ version: 2020.2
- Intellij-rsp extension version: built from master

## What did you run exactly?
Created CDK from local folder, fill in all necessary info, server is created
Run server action -> setup-cdk

## Actual behavior
Nothing happens, error is thrown in error location

## Expected behavior
Output channel is opened, output is logged there and actions is performed

## Any logs, error output, etc?
java.lang.NullPointerException
	at org.jboss.tools.intellij.rsp.ui.util.WorkflowUiUtility.displayPromptsSeekWorkflowInput(WorkflowUiUtility.java:47)
	at org.jboss.tools.intellij.rsp.actions.ServerActionAction.initiateActionWorkflow(ServerActionAction.java:82)
	at org.jboss.tools.intellij.rsp.actions.ServerActionAction.access$000(ServerActionAction.java:33)
	at org.jboss.tools.intellij.rsp.actions.ServerActionAction$1.run(ServerActionAction.java:69)

**Comment by robstryker** [comment]
Line 47 reads:

`for( WorkflowResponseItem i : items ) {`

Items should never ever be null. It certainly isn't null for the setup-crc command. Code on the rsp-server shows clearly it cannot be null during this action. Something else must be happening.

**Comment by robstryker** [comment]
I'll add a null check just for completeness I guess.
